# -*- coding: utf-8 -*-
"""Time series-wordcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OReJECqbvn9ZSUYVKDch9ngYcaMdgIJn
"""

import pandas as pd
import matplotlib.pyplot as plt

data={"date":pd.to_datetime(["2022-01-01","2022-02-01","2022-03-01","2022-04-01","2022-05-01"]),
                            "value":[10,15,22,28,35]}
df=pd.DataFrame(data)
df.set_index("date",inplace=True)
plt.figure(figsize=(10,6))
plt.plot(df.index,df["value"],marker='x')
plt.xlabel("date")
plt.ylabel("value")
plt.title("time series with trend")
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

import pandas as pd
import matplotlib.pyplot as plt

data={"date":pd.to_datetime(["2022-01-01","2022-02-01","2022-03-01","2022-04-01","2022-05-01","2022-06-01","2023-03-01","2023-04-01"]),
                            "value":[5,10,20,30,15,12,20,30]}
df=pd.DataFrame(data)
df.set_index("date",inplace=True)
plt.figure(figsize=(10,6))
plt.plot(df.index,df["value"],marker='x')
plt.xlabel("date")
plt.ylabel("value")
plt.title("Time series with Seasonality ")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
from wordcloud import WordCloud
from collections import Counter
text_data="chandu rishitha varshini bairu"
wordcloud=WordCloud(width=800,height=400,background_color='black').generate(text_data)
plt.figure(figsize=(10,5))
plt.imshow(wordcloud)
plt.title('word cloud')
plt.axis('off')
plt.show()
words=text_data.split()
word_counts=Counter(words)
plt.figure(figsize=(10,5))
plt.bar(word_counts.keys(),word_counts.values())
plt.title('histogram of words frequency')
plt.xlabel('words')
plt.ylabel('frequency')
plt.xticks(rotation=90)
plt.show

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
def remove_stop_words(String):
  stop_words=set(stopwords.words('english'))
  words=String.split()
  filtered_words=[word for word in words if word.lower()not in stop_words]
  new_String=''.join(filtered_words)
  return new_String
  input_String="This is an example sentence to remove stopwords from"
  resulit=remove_stop_words(input_String)
  print("original String:",input_String)
  print("Modified String",result)

